// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using planar.server.Models;

namespace planar.server.Migrations
{
    [DbContext(typeof(PlanarContext))]
    [Migration("20200722171001_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0-preview.7.20365.15");

            modelBuilder.Entity("planar.server.Models.Buff", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long?>("Locationid")
                        .HasColumnType("bigint");

                    b.Property<long?>("Planeid")
                        .HasColumnType("bigint");

                    b.Property<bool>("locked")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("revealed")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("Locationid");

                    b.HasIndex("Planeid");

                    b.ToTable("buffs");
                });

            modelBuilder.Entity("planar.server.Models.Character", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("locked")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("race")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("revealed")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("LocationId");

                    b.ToTable("characters");
                });

            modelBuilder.Entity("planar.server.Models.Location", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long>("PlaneId")
                        .HasColumnType("bigint");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("locked")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("revealed")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("PlaneId");

                    b.ToTable("locations");
                });

            modelBuilder.Entity("planar.server.Models.Plane", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("locked")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("revealed")
                        .HasColumnType("bit");

                    b.Property<int>("ring")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("planes");
                });

            modelBuilder.Entity("planar.server.Models.Quest", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long?>("Locationid")
                        .HasColumnType("bigint");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("giverid")
                        .HasColumnType("bigint");

                    b.Property<bool>("locked")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("revealed")
                        .HasColumnType("bit");

                    b.Property<string>("reward")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Locationid");

                    b.HasIndex("giverid");

                    b.ToTable("quests");
                });

            modelBuilder.Entity("planar.server.Models.Buff", b =>
                {
                    b.HasOne("planar.server.Models.Location", null)
                        .WithMany("buffs")
                        .HasForeignKey("Locationid");

                    b.HasOne("planar.server.Models.Plane", null)
                        .WithMany("buffs")
                        .HasForeignKey("Planeid");
                });

            modelBuilder.Entity("planar.server.Models.Character", b =>
                {
                    b.HasOne("planar.server.Models.Location", null)
                        .WithMany("characters")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("planar.server.Models.Location", b =>
                {
                    b.HasOne("planar.server.Models.Plane", null)
                        .WithMany("locations")
                        .HasForeignKey("PlaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("planar.server.Models.Quest", b =>
                {
                    b.HasOne("planar.server.Models.Location", null)
                        .WithMany("quests")
                        .HasForeignKey("Locationid");

                    b.HasOne("planar.server.Models.Character", "giver")
                        .WithMany()
                        .HasForeignKey("giverid");
                });
#pragma warning restore 612, 618
        }
    }
}
